package org.axan.sep.common.db;

import org.axan.sep.common.db.orm.SEPCommonDB;

/**
 * A command is a game event that can be generated by client and send to server as part of the end of turn commands list.
 */
public interface ICommand extends IGameEvent
{
	public static class GameCommandException extends GameEventException
	{
		private static final long	serialVersionUID	= 1L;

		public GameCommandException(ICommand command, Throwable t)
		{
			super(command, t);
		}

		public GameCommandException(ICommand command, String msg)
		{
			super(command, msg);
		}
		
		@Override
		public ICommand getEvent()
		{
			return (ICommand) super.getEvent();
		}				
	}
	
	void check(SEPCommonDB db) throws GameCommandException;
}
